version: "3"
services:
  slim-chat-back:
    build:
      context: .
    command: npm run start
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: example123
      POSTGRES_USER: edimario
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
